export const createBoardButtonStepOne = "[data-testid='create-board-tile']"
export const createBoardTitle = "[data-testid='create-board-title-input']"
export const createBoardButtonStepTwo = "[data-testid='create-board-button']"
export const createBoardButtonStepThree = "[data-testid='create-board-submit-button']"
export const boardTile = "a[aria-label='Test Board']"
export const clickHorizontalThreeDotsTestBoard = "[aria-label='Show menu']"
export const closeBoardButton = "text=Close board"
export const redCloseBoardButtonPopup = "[data-testid='popover-close-board-confirm']"
export const permanentDeleteBoardButton = "[data-testid='close-board-delete-board-button']"
export const redDeleteBoardConfirmButtonPopup = "[data-testid='close-board-delete-board-confirm-button']"
export const createListButton = "[data-testid='list-composer-button']"
export const addListName = "[data-testid='list-name-textarea']"
export const addListButton = "[data-testid='list-composer-add-list-button']"
export const listNameonBoard = "[data-testid='list-name']"
export const addCardButtonInToDoList = "[data-testid='list-add-card-button'][aria-label='Add a card in To Do']"
export const addCardTextBoxInToDoList = "[data-testid='list-card-composer-textarea']"
export const addCardButtonFinalInToDoList = "[data-testid='list-card-composer-add-card-button'][aria-label='Add card in To Do']"
export const cardNameonBoard = "[data-testid='card-name']"